name: toast_service
description: A starting point for Dart libraries or applications.
version: 2.0.3

environment:
  sdk: ">=3.5.4 < 4.0.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.16.0
dependencies:
  fluttertoast: ^8.1.2
  flutter:
    sdk: flutter
  material: ^1.0.0+2
