name: toast_service
description: A starting point for Dart libraries or applications.
version: 1.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  fluttertoast: ^8.1.2
  flutter:
    sdk: flutter
  material: ^1.0.0+2
